export interface Song {
  id: string;
  name: string;
  artist: string;
}

// 100 tracks from Spotify playlist 3k6Os3T678g6MNfcN5u3SX ("6 MINUTES!! Songs you should know (2)")
export const songs: Song[] = [
  { id: "3gdewACMIVMEWVbyb8O9sY", name: "Rocket Man (I Think It's Going To Be A Long, Long Time)", artist: "Elton John" },
  { id: "2H3ZUSE54pST4ubRd5FzFR", name: "Ain't No Mountain High Enough", artist: "Marvin Gaye, Tammi Terrell" },
  { id: "2iJuuzV8P9Yz0VSurttIV5", name: "Scream & Shout", artist: "will.i.am, Britney Spears" },
  { id: "05wIrZSwuaVWhcv5FfqeH0", name: "Walking On Sunshine", artist: "Katrina & The Waves" },
  { id: "7tFiyTwD0nx5a1eklYtX2J", name: "Bohemian Rhapsody - Remastered 2011", artist: "Queen" },
  { id: "1PS1QMdUqOal0ai3Gt7sDQ", name: "Gold Digger", artist: "Kanye West, Jamie Foxx" },
  { id: "6e40mgJiCid5HRAGrbpGA6", name: "I Want It That Way", artist: "Backstreet Boys" },
  { id: "3LI5sEv27CBupQoAg1VN2D", name: "Wicked Wonderland", artist: "Tungevaag" },
  { id: "3TGRqZ0a2l1LRblBkJoaDx", name: "Call Me Maybe", artist: "Carly Rae Jepsen" },
  { id: "6RcQOut9fWL6FSqeIr5M1r", name: "Hollaback Girl", artist: "Gwen Stefani" },
  { id: "40riOy7x9W7GXjyGp4pjAv", name: "Hotel California - 2013 Remaster", artist: "Eagles" },
  { id: "52xaypL0Kjzk0ngwv3oBPR", name: "Beat It", artist: "Michael Jackson" },
  { id: "40ogYHQCVmrUJ2jCiM2odT", name: "I Follow Rivers - The Magician Remix", artist: "Lykke Li, The Magician" },
  { id: "4bHsxqR3GMrXTxEPLuK5ue", name: "Don't Stop Believin'", artist: "Journey" },
  { id: "5vdp5UmvTsnMEMESIF2Ym7", name: "Another One Bites The Dust - Remastered 2011", artist: "Queen" },
  { id: "0ikz6tENMONtK6qGkOrU3c", name: "Wake Me Up Before You Go-Go", artist: "Wham!" },
  { id: "234KktmIe84z77j8DBofgE", name: "Afterski", artist: "Broiler" },
  { id: "2374M0fQpWi3dLnB54qaLX", name: "Africa", artist: "TOTO" },
  { id: "1gv4xPanImH17bKZ9rOveR", name: "Raise Your Glass", artist: "P!nk" },
  { id: "70C4NyhjD5OZUMzvWZ3njJ", name: "Piano Man", artist: "Billy Joel" },
  { id: "5ChkMS8OtdzJeqyybCc9R5", name: "Billie Jean", artist: "Michael Jackson" },
  { id: "37ZJ0p5Jm13JPevGcx4SkF", name: "Livin' On A Prayer", artist: "Bon Jovi" },
  { id: "5zA8vzDGqPl2AzZkEYQGKh", name: "Uptown Girl", artist: "Billy Joel" },
  { id: "7e89621JPkKaeDSTQ3avtg", name: "Sweet Home Alabama", artist: "Lynyrd Skynyrd" },
  { id: "2HHtWyy5CgaQbC7XSoOb0e", name: "Eye of the Tiger", artist: "Survivor" },
  { id: "4uLU6hMCjMI75M1A2tKUQC", name: "Never Gonna Give You Up", artist: "Rick Astley" },
  { id: "2tUBqZG2AbRi7Q0BIrVrEj", name: "I Wanna Dance with Somebody (Who Loves Me)", artist: "Whitney Houston" },
  { id: "7HW5WIw7ZgZORCzUxv5gW5", name: "Don't Go Breaking My Heart", artist: "Elton John, Kiki Dee" },
  { id: "5IVuqXILoxVWvWEPm82Jxr", name: "Crazy In Love (feat. JAY-Z)", artist: "Beyonce, JAY-Z" },
  { id: "7hQJA50XrCWABAu5v6QZ4i", name: "Don't Stop Me Now - Remastered 2011", artist: "Queen" },
  { id: "09ISyLOPeuno7kKlzdbZuq", name: "Stamp on the Ground - Radio Edit", artist: "ItaloBrothers" },
  { id: "6tXjP6xgPJ7Xr1igrO6bOE", name: "Don't Stop The Music", artist: "Rihanna" },
  { id: "6s8nHXTJVqFjXE4yVZPDHR", name: "Troublemaker (feat. Flo Rida)", artist: "Olly Murs, Flo Rida" },
  { id: "2u8MGAiS2hBVE7GZzTZLQI", name: "I'm So Excited", artist: "The Pointer Sisters" },
  { id: "6IWkdrBY2O0vfQdfEKGUdF", name: "September", artist: "Earth, Wind & Fire" },
  { id: "5ZrDlcxIDZyjOzHdYW1ydr", name: "Barbie Girl", artist: "Aqua" },
  { id: "3cfOd4CMv2snFaKAnMdnvK", name: "All Star", artist: "Smash Mouth" },
  { id: "0D4BrT1XkauoXF8R2dFg1A", name: "Etter Regnet", artist: "Erik Og Kriss" },
  { id: "6DCZcSspjsKoFjzjrWoCdn", name: "God's Plan", artist: "Drake" },
  { id: "6lV2MSQmRIkycDScNtrBXO", name: "Airplanes (feat. Hayley Williams of Paramore)", artist: "B.o.B, Hayley Williams" },
  { id: "0e7ipj03S05BNilyu5bRzt", name: "rockstar (feat. 21 Savage)", artist: "Post Malone, 21 Savage" },
  { id: "7BKLCZ1jbUBVqRi2FVlTVw", name: "Closer", artist: "The Chainsmokers, Halsey" },
  { id: "1qE47wUKG2juJwPoLqg4C9", name: "Lean On (feat. MO & DJ Snake)", artist: "Major Lazer, MO, DJ Snake" },
  { id: "0TVV2gFROJaB3kIZyCUvIY", name: "Rather Be (feat. Jess Glynne)", artist: "Clean Bandit, Jess Glynne" },
  { id: "6YUTL4dYpB9xZO5qExPf05", name: "Summer", artist: "Calvin Harris" },
  { id: "32OlwWuMpZ6b0aN2RZOeMS", name: "Uptown Funk (feat. Bruno Mars)", artist: "Mark Ronson, Bruno Mars" },
  { id: "4G8gkOterJn0Ywt6uhqbhp", name: "Radioactive", artist: "Imagine Dragons" },
  { id: "2JzZzZUQj3Qff7wapcbKjc", name: "See You Again (feat. Charlie Puth)", artist: "Wiz Khalifa, Charlie Puth" },
  { id: "7vFoFDWqTX0mHzLfrF1Cfy", name: "Cheerleader (Felix Jaehn Remix) - Radio Edit", artist: "OMI, Felix Jaehn" },
  { id: "1CkvWZme3pRgbzaxZnTl5X", name: "Rolling in the Deep", artist: "Adele" },
  { id: "1qDrWA6lyx8cLECdZE7TV7", name: "Somebody That I Used To Know", artist: "Gotye, Kimbra" },
  { id: "6ocbgoVGwYJhOv1GgI9NsF", name: "7 rings", artist: "Ariana Grande" },
  { id: "5b88tNINg4Q4nrRbrCXUmg", name: "Happy - From \"Despicable Me 2\"", artist: "Pharrell Williams" },
  { id: "6RUKPb4LETWmmr3iAEQktW", name: "Something Just Like This", artist: "The Chainsmokers, Coldplay" },
  { id: "4h8VwCb1MTGoLKueQ1WgbD", name: "Wake Me Up", artist: "Avicii" },
  { id: "3U4isOIWM3VvDubwSI3y7a", name: "All of Me", artist: "John Legend" },
  { id: "2YpeDb67231RjR0MgVLzsG", name: "Old Town Road (feat. Billy Ray Cyrus) - Remix", artist: "Lil Nas X, Billy Ray Cyrus" },
  { id: "0Oe49j06Bjrxs8PltuVeaW", name: "On The Floor - Radio Edit", artist: "Jennifer Lopez, Pitbull" },
  { id: "6v3KW9xbzN5yKLt9YKDYA2", name: "Senorita", artist: "Shawn Mendes, Camila Cabello" },
  { id: "2a1o6ZejUi8U3wzzOtCOYw", name: "Danza Kuduro", artist: "Don Omar, Lucenzo" },
  { id: "3bC1ahPIYt1btJzSSEyyrF", name: "Whistle", artist: "Flo Rida" },
  { id: "0AH6WMe3OlAlUb5miXt2FQ", name: "Only Girl (In The World)", artist: "Rihanna" },
  { id: "2Cd9iWfcOpGDHLz6tVA3G4", name: "Waka Waka (This Time for Africa)", artist: "Shakira, Freshlyground" },
  { id: "2Fxmhks0bxGSBdJ92vM42m", name: "bad guy", artist: "Billie Eilish" },
  { id: "3ee8Jmje8o58CHK66QrVC2", name: "SAD!", artist: "XXXTENTACION" },
  { id: "5jrdCoLpJSvHHorevXBATy", name: "Dark Horse", artist: "Katy Perry, Juicy J" },
  { id: "0QsvXIfqM0zZoerQfsI9lm", name: "Don't Let Me Down", artist: "The Chainsmokers, Daya" },
  { id: "7Ie9W94M7OjPoZVV216Xus", name: "Not Afraid", artist: "Eminem" },
  { id: "1oHNvJVbFkexQc0BpQp7Y4", name: "Starships", artist: "Nicki Minaj" },
  { id: "2G7V7zsVDxg1yRsu7Ew9RJ", name: "In My Feelings", artist: "Drake" },
  { id: "1zi7xx7UVEFkmKfv06H8x0", name: "One Dance", artist: "Drake, Wizkid, Kyla" },
  { id: "0RiRZpuVRbi7oqRdSMwhQY", name: "Sunflower - Spider-Man: Into the Spider-Verse", artist: "Post Malone, Swae Lee" },
  { id: "1Slwb6dOYkBlWal1PGtnNg", name: "Thinking out Loud", artist: "Ed Sheeran" },
  { id: "6habFhsOp2NvshLv26DqMb", name: "Despacito", artist: "Luis Fonsi, Daddy Yankee" },
  { id: "7qiZfU4dY1lWllzX7mPBI3", name: "Shape of You", artist: "Ed Sheeran" },
  { id: "7KXjTSCq5nL1LoYtL7XAwS", name: "HUMBLE.", artist: "Kendrick Lamar" },
  { id: "2jyjhRf6DVbMPU5zxagN2h", name: "Let Her Go", artist: "Passenger" },
  { id: "3swc6WTsr7rl9DqQKQA55C", name: "Psycho (feat. Ty Dolla $ign)", artist: "Post Malone, Ty Dolla $ign" },
  { id: "15JINEqzVMv3SvJTAXAKED", name: "Love The Way You Lie", artist: "Eminem, Rihanna" },
  { id: "4lLtanYk6tkMvooU0tWzG8", name: "Grenade", artist: "Bruno Mars" },
  { id: "27SdWb2rFzO6GWiYDBTD9j", name: "Cheap Thrills", artist: "Sia" },
  { id: "1MtUq6Wp1eQ8PC6BbPCj8P", name: "I Took A Pill In Ibiza - Seeb Remix", artist: "Mike Posner, Seeb" },
  { id: "3AYcxEACnmE6d96RPubID", name: "Thrift Shop (feat. Wanz)", artist: "Macklemore & Ryan Lewis, Wanz" },
  { id: "2P4OICZRVAQcYAV2JReRfj", name: "Waiting For Love", artist: "Avicii" },
  { id: "4650WGL6InVqP7YN5POqIz", name: "Party Rock Anthem", artist: "LMFAO, Lauren Bennett, GoonRock" },
  { id: "5rgy6ghBq1eRApCkeUdJXf", name: "We Are Young (feat. Janelle Monae)", artist: "fun., Janelle Monae" },
  { id: "3bidbhpOYeV4knp8AIu8Xn", name: "Can't Hold Us (feat. Ray Dalton)", artist: "Macklemore, Ryan Lewis" },
  { id: "1B75hgRqe7A4fwee3g3Wmu", name: "U Can't Touch This", artist: "MC Hammer" },
  { id: "1vxw6aYJls2oq3gW0DujAo", name: "Crazy", artist: "Gnarls Barkley" },
  { id: "0I9KnKdIVz8envRSA6yGZL", name: "Hot Stuff - 12\" Version", artist: "Donna Summer" },
  { id: "2Tk5B1h58lJRsrivGg1jaE", name: "Vamos a la Playa", artist: "Loona" },
  { id: "6zKMARmU2Ue50cucKnIUR6", name: "Forget You", artist: "CeeLo Green" },
  { id: "11d9oUiwHuYt216EFA2tiz", name: "Ice Ice Baby", artist: "Vanilla Ice" },
  { id: "6ztstiyZL6FXzh4aG46ZPD", name: "Boogie Wonderland (with The Emotions)", artist: "Earth, Wind & Fire, The Emotions" },
  { id: "3WMbD1OyfKuwWDWMNbPQ4g", name: "Daddy Cool", artist: "Boney M." },
  { id: "0cqRj7pUJDkTCEsJkx8snD", name: "Shake It Off", artist: "Taylor Swift" },
];
